### PR TITLE
Crashdown rails 5 june

### PR DESCRIPTION
**Pull request by brentdodell**

### CODE REVIEW

**Comment by clintmiller** [comment]
Things we need to verify in this branch:

- [x] `base_switch` is no longer a concern? That means we don't have to worry about inconsistent switching or potential deadlocking for any of the migration or database creation -related Rake tasks?
- [x] Correct query cache behavior
- [x] Connection pool behavior: looks like we'll be falling back to an ActiveRecord implementation of connection pooling. This feels like an important behavior to validate.

**Comment by tpett** [comment]
`base_switch` is now always the behavior. We are always switching on the `AR::Base` class which was the original intent of `base_switch` (which we added by the way--I hadn't realized that before). We don't need to have two different switches now.

I don't believe the query cache code has changed. The `clear_query_cache` method is still being called in the `switch!` method as before. It seems to be functioning as I would expect in the Crashdown Rails 5 branch.

@brentdodell had a little test where he printed out the `object_id`s of all the connection pools several times while performing switching operations and they were all the same indicating that we are reusing the same connection pools like we were doing before. The difference is that before, we were stashing the connection pool away in a class we created named for the tenant, but now we are stashing the connection pool in the connection handler hash named by the tenant. This way we can simply set the `connection_specification_name` on any AR class and get back the specified tenant.

**Comment by brentdodell** [comment]
> @brentdodell had a little test where he printed out the object_ids of all the connection pools several times while performing switching operations and they were all the same indicating that we are reusing the same connection pools like we were doing before.

This is what I have used to validate before. I could have saved object ids and compared them with `==` to make it easier, but I just verified it manually by looking at them.

```
TenantSwitcher.(tenant: :graceway) do
  ap Customer.connection_handler.connection_pools.map { |cp| { cp.spec.name => cp.object_id } }
  ap Customer.first.email

  TenantSwitcher.(tenant: :igniter) do
    ap Customer.connection_handler.connection_pools.map { |cp| { cp.spec.name => cp.object_id } }
    ap Customer.first.email

    TenantSwitcher.(tenant: :graceway) do
      ap Customer.connection_handler.connection_pools.map { |cp| { cp.spec.name => cp.object_id } }
      ap Customer.first.email
    end

    ap Customer.connection_handler.connection_pools.map { |cp| { cp.spec.name => cp.object_id } }
    ap Customer.first.email
  end

  ap Customer.connection_handler.connection_pools.map { |cp| { cp.spec.name => cp.object_id } }
  ap Customer.first.email
end
```

**Comment by clintmiller** [comment]
For monitoring DB connection counts...which hopefully reveals any connection pooling issues: https://ops.rtpcore.com/grafana/dashboard/db/database-performance-monitoring

**Comment by brentdodell** [comment]
@tpett did you happen to notice [this error](http://errbit.rtpcore.com/apps/5665f9a5373864001c000001/problems/595282fee495d000140026f4)? I'm not quite sure how to replicate it. It appears to be happening on [this line](https://github.com/rtcreativegroup/apartment/pull/7/files#diff-3c1648ae31d9d2ce5c1a1ec6dfe2d1d2R182), which would make sense because [connected?](https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L938-L939) calls [retrieve_connection](https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L928-L932), which is raising the error. 

What I don't understand is why we aren't seeing that error every time we try to connect to a tenant for the first time. I've only seen it once while running in production on `ia2`. I feel like I remember it being right after I restarted sidekiq...but I'm not 100% on that, and I don't know if that's pertinent if it was...seems like it could be.

Also, I was wondering if [this](https://github.com/rtcreativegroup/apartment/compare/crashdown-rails-5-june...rtcreativegroup:crashdown-rails-5-june-attempt-to-fix-tenant-not-found?expand=1) would be a valid change. If it is, I think it would resolve this issue...I just don't know whether it would do the right thing where `ConnectionPool`/`Connection`s are concerned (whatever that right thing is). Also, if valid, that change [simplifies our diff](https://github.com/rtcreativegroup/apartment/compare/master...rtcreativegroup:crashdown-rails-5-june-attempt-to-fix-tenant-not-found?expand=1#diff-3c1648ae31d9d2ce5c1a1ec6dfe2d1d2) for `AbstractAdapter`.

**EDIT!!!**
Previously, I had said that `connected?` calls `retrieve_connection`, which throws the error we're getting...but it doesn't call `retrieve_connection`, it calls `retrieve_connection_pool` so that makes even less sense why [this line]() would be throwing the error. `connected?` should return `false` the first time we attempt to connect to a tenant connection pool, which should try to establish a new connection.

That being said, I'm still curious if you think the changes I listed would be valid, and if so, that *might* fix the issue since we wouldn't be checking the `connected?` state ourselves, but would be trying to establish a new connection (within the correct pool) each time, letting the connection pool just do it's thing.

**Comment by tpett** [comment]
I hadn't seen that yet. The issue I would be concerned about there is calling `establish_connection` every time we do a tenant switch. I think that would cause the database connection to be reconnected on every tenant switch. You could check if `connection_handler` has a spec defined by that name and then if it does check if it is also connected. That would be a way around that error at least.

I'm guessing that the error has something to do with the multithreaded nature of Sidekiq, but I'm not quite sure why it would happen off the top of my head.

**Comment by brentdodell** [comment]
> You could check if connection_handler has a spec defined by that name and then if it does check if it is also connected. That would be a way around that error at least.

Like this (168803d)?

**Comment by clintmiller** [comment]
I'm 👍 on integrating this, but it should probably target a long-lived branch, `crashdown-five`, right?

**Pull request merged**
